# This file was generated by GoReleaser. DO NOT EDIT.
cask "macform" do
  version "0.0.15"

  on_macos do
    on_intel do
      sha256 "f57e4f66afc134fdc9c688287c56b693c532d37742858bf54369ca1f69256a73"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa276933791e28df0aa4c95ec3a2a3929208fea5b11ba7973721d6dd31cf7244"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "macform"
  desc "Declarative macOS system settings management"
  homepage "https://github.com/vsimon/macform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macform"

  # No zap stanza required

end
