# This file was generated by GoReleaser. DO NOT EDIT.
cask "macform" do
  version "0.0.22"

  on_macos do
    on_intel do
      sha256 "c6cd203d64956aae1a3f40adbacbef54a9937f47d4637ef0620e816432387978"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a0ae7edba9eb4fd49e804fd8c9798b471e9af979f4d0466111327ef65477766"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "macform"
  desc "Declarative macOS system settings management"
  homepage "https://github.com/vsimon/macform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macform"

  # No zap stanza required

end
