# This file was generated by GoReleaser. DO NOT EDIT.
cask "macform" do
  version "0.0.19"

  on_macos do
    on_intel do
      sha256 "e151814d09e4303dd98df0171041a2c2ca9f872f24d5be3b6530f522104f1b08"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aee91a960fad158560209c8dc88c2a934aff8e0f01d0399d98b08e0992438f6f"
      url "https://github.com/vsimon/macform/releases/download/v#{version}/macform_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "macform"
  desc "Declarative macOS system settings management"
  homepage "https://github.com/vsimon/macform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macform"

  # No zap stanza required

end
